const ERA_COLORS = {
  "Early Music":   "#8fbc5a",
  "Renaissance":   "#c8a96e",
  "Baroque":       "#e07b39",
  "Classical Era": "#4a90d9",
  "Romantic Era":  "#c0392b",
  "Nationalism":   "#8e44ad",
  "Modern Era":    "#6c3483",
  "Contemporary":  "#c0397b"
};

const ERA_PAGES = {
  "Early Music":   "early-music.html",
  "Renaissance":   "renaissance.html",
  "Baroque":       "baroque.html",
  "Classical Era": "classical-era.html",
  "Romantic Era":  "romantic.html",
  "Nationalism":   "nationalism.html",
  "Modern Era":    "modern.html",
  "Contemporary":  "contemporary.html"
};

const COMPOSERS = [
  { name:"Guido D'Arezzo",          era:"Early Music",   born:991,  died:1033, work:"Micrologus — invented staff notation" },
  { name:"Hildegard of Bingen",     era:"Early Music",   born:1098, died:1179, work:"Ordo Virtutum" },
  { name:"Léonin",                  era:"Early Music",   born:1150, died:1201, work:"Magnus liber organi" },
  { name:"Adam de la Halle",        era:"Early Music",   born:1245, died:1288, work:"Le Jeu de Robin et de Marion" },
  { name:"Guillaume de Machaut",    era:"Early Music",   born:1300, died:1377, work:"Messe de Notre Dame" },
  { name:"Guillaume Dufay",         era:"Renaissance",   born:1397, died:1474, work:"Missa L'homme armé" },
  { name:"Josquin Desprez",         era:"Renaissance",   born:1450, died:1521, work:"Missa Pange lingua" },
  { name:"Thomas Tallis",           era:"Renaissance",   born:1505, died:1585, work:"Spem in alium" },
  { name:"Giovanni da Palestrina",  era:"Renaissance",   born:1525, died:1594, work:"Canticum Canticorum" },
  { name:"William Byrd",            era:"Renaissance",   born:1543, died:1623, work:"Great Service" },
  { name:"Giovanni Gabrieli",       era:"Renaissance",   born:1554, died:1612, work:"Sonata pian' e forte" },
  { name:"John Dowland",            era:"Renaissance",   born:1563, died:1626, work:"Lachrimae" },
  { name:"Thomas Weelkes",          era:"Renaissance",   born:1576, died:1623, work:"O Care, Thou Wilt Despatch Me" },
  { name:"Jacopo Peri",             era:"Baroque",       born:1561, died:1633, work:"Euridice — first opera" },
  { name:"Claudio Monteverdi",      era:"Baroque",       born:1567, died:1643, work:"Vespers, L'Orfeo" },
  { name:"Jean-Baptiste Lully",     era:"Baroque",       born:1632, died:1687, work:"Le bourgeois gentilhomme" },
  { name:"Dieterich Buxtehude",     era:"Baroque",       born:1637, died:1707, work:"Ein feste Burg" },
  { name:"Arcangelo Corelli",       era:"Baroque",       born:1653, died:1713, work:"Concerti grossi Op.6" },
  { name:"Henry Purcell",           era:"Baroque",       born:1659, died:1695, work:"Dido and Aeneas" },
  { name:"François Couperin",       era:"Baroque",       born:1668, died:1733, work:"Pièces de clavecin" },
  { name:"Antonio Vivaldi",         era:"Baroque",       born:1678, died:1741, work:"The Four Seasons" },
  { name:"Georg Philipp Telemann",  era:"Baroque",       born:1681, died:1767, work:"Musique de table" },
  { name:"Jean-Philippe Rameau",    era:"Baroque",       born:1683, died:1764, work:"Hippolyte et Aricie" },
  { name:"George Frideric Handel",  era:"Baroque",       born:1685, died:1759, work:"Messiah, Water Music" },
  { name:"Domenico Scarlatti",      era:"Baroque",       born:1685, died:1757, work:"555 Keyboard Sonatas" },
  { name:"Johann Sebastian Bach",   era:"Baroque",       born:1685, died:1750, work:"St. Matthew Passion" },
  { name:"Christoph Willibald Gluck",era:"Classical Era",born:1714, died:1787, work:"Orfeo ed Euridice" },
  { name:"Carl Philipp Emanuel Bach",era:"Classical Era",born:1714, died:1788, work:"Flute Concerto" },
  { name:"Johann Stamitz",          era:"Classical Era", born:1717, died:1757, work:"Mannheim Symphonies" },
  { name:"Joseph Haydn",            era:"Classical Era", born:1732, died:1809, work:"The Creation" },
  { name:"Muzio Clementi",          era:"Classical Era", born:1752, died:1832, work:"Piano Sonatas" },
  { name:"Wolfgang Amadeus Mozart", era:"Classical Era", born:1756, died:1791, work:"Don Giovanni, Symphony No.40" },
  { name:"Ludwig van Beethoven",    era:"Classical Era", born:1770, died:1827, work:"Eroica, Symphony No.9" },
  { name:"Niccolò Paganini",        era:"Romantic Era",  born:1782, died:1840, work:"24 Caprices" },
  { name:"Franz Schubert",          era:"Romantic Era",  born:1797, died:1828, work:"Winterreise" },
  { name:"Hector Berlioz",          era:"Romantic Era",  born:1803, died:1869, work:"Symphonie fantastique" },
  { name:"Felix Mendelssohn",       era:"Romantic Era",  born:1809, died:1847, work:"Elijah, Violin Concerto" },
  { name:"Frédéric Chopin",         era:"Romantic Era",  born:1810, died:1849, work:"Préludes, Ballades" },
  { name:"Robert Schumann",         era:"Romantic Era",  born:1810, died:1856, work:"Dichterliebe" },
  { name:"Franz Liszt",             era:"Romantic Era",  born:1811, died:1886, work:"Piano Sonata in B minor" },
  { name:"Richard Wagner",          era:"Romantic Era",  born:1813, died:1883, work:"The Ring Cycle" },
  { name:"Giuseppe Verdi",          era:"Romantic Era",  born:1813, died:1901, work:"La traviata, Otello" },
  { name:"Johann Strauss II",       era:"Romantic Era",  born:1825, died:1899, work:"The Blue Danube" },
  { name:"Johannes Brahms",         era:"Romantic Era",  born:1833, died:1897, work:"Symphony No.1" },
  { name:"Camille Saint-Saëns",     era:"Romantic Era",  born:1835, died:1921, work:"Symphony No.3 Organ" },
  { name:"Pyotr Ilyich Tchaikovsky",era:"Romantic Era",  born:1840, died:1893, work:"The Nutcracker" },
  { name:"Richard Strauss",         era:"Romantic Era",  born:1864, died:1949, work:"Also sprach Zarathustra" },
  { name:"Giacomo Puccini",         era:"Romantic Era",  born:1858, died:1924, work:"La Bohème, Tosca" },
  { name:"Gustav Mahler",           era:"Romantic Era",  born:1860, died:1911, work:"Das Lied von der Erde" },
  { name:"Bedřich Smetana",         era:"Nationalism",   born:1824, died:1884, work:"Má vlast" },
  { name:"Modest Mussorgsky",       era:"Nationalism",   born:1839, died:1881, work:"Pictures at an Exhibition" },
  { name:"Antonín Dvořák",          era:"Nationalism",   born:1841, died:1904, work:"New World Symphony" },
  { name:"Edvard Grieg",            era:"Nationalism",   born:1843, died:1907, work:"Peer Gynt" },
  { name:"Gabriel Fauré",           era:"Nationalism",   born:1845, died:1924, work:"Requiem" },
  { name:"Edward Elgar",            era:"Nationalism",   born:1857, died:1934, work:"Enigma Variations" },
  { name:"Isaac Albéniz",           era:"Nationalism",   born:1860, died:1909, work:"Iberia" },
  { name:"Jean Sibelius",           era:"Nationalism",   born:1865, died:1957, work:"Finlandia" },
  { name:"Manuel de Falla",         era:"Nationalism",   born:1876, died:1946, work:"El sombrero de tres picos" },
  { name:"Leoš Janáček",            era:"Modern Era",    born:1854, died:1928, work:"Sinfonietta" },
  { name:"Ethel Smyth",             era:"Modern Era",    born:1858, died:1944, work:"The Wreckers" },
  { name:"Claude Debussy",          era:"Modern Era",    born:1862, died:1918, work:"Prélude à l'après-midi d'un faune" },
  { name:"Erik Satie",              era:"Modern Era",    born:1866, died:1925, work:"Gymnopédies, Parade" },
  { name:"Ralph Vaughan Williams",  era:"Modern Era",    born:1872, died:1958, work:"The Lark Ascending" },
  { name:"Arnold Schoenberg",       era:"Modern Era",    born:1874, died:1951, work:"Pierrot lunaire" },
  { name:"Charles Ives",            era:"Modern Era",    born:1874, died:1954, work:"Symphony No.4" },
  { name:"Maurice Ravel",           era:"Modern Era",    born:1875, died:1937, work:"Boléro, Piano Concerto Left Hand" },
  { name:"Béla Bartók",             era:"Modern Era",    born:1881, died:1945, work:"String Quartets" },
  { name:"Igor Stravinsky",         era:"Modern Era",    born:1882, died:1971, work:"The Rite of Spring" },
  { name:"Anton von Webern",        era:"Modern Era",    born:1883, died:1945, work:"Symphonie Op.21" },
  { name:"Edgard Varèse",           era:"Modern Era",    born:1883, died:1965, work:"Ionisation" },
  { name:"Heitor Villa-Lobos",      era:"Modern Era",    born:1887, died:1959, work:"Bachianas brasileiras" },
  { name:"Sergei Prokofiev",        era:"Modern Era",    born:1891, died:1953, work:"Romeo and Juliet" },
  { name:"George Gershwin",         era:"Modern Era",    born:1898, died:1937, work:"Rhapsody in Blue" },
  { name:"Francis Poulenc",         era:"Modern Era",    born:1899, died:1963, work:"Dialogues of the Carmelites" },
  { name:"Colin McPhee",            era:"Modern Era",    born:1900, died:1964, work:"Tabuh-Tabuhan" },
  { name:"Aaron Copland",           era:"Modern Era",    born:1900, died:1990, work:"Appalachian Spring" },
  { name:"Michael Tippett",         era:"Modern Era",    born:1905, died:1998, work:"A Child of Our Time" },
  { name:"Dmitri Shostakovich",     era:"Modern Era",    born:1906, died:1975, work:"Symphony No.5" },
  { name:"Olivier Messiaen",        era:"Modern Era",    born:1908, died:1992, work:"Quartet for the End of Time" },
  { name:"Benjamin Britten",        era:"Modern Era",    born:1913, died:1976, work:"Peter Grimes, War Requiem" },
  { name:"Aram Khachaturian",       era:"Contemporary",  born:1903, died:1978, work:"Spartacus" },
  { name:"Pierre Schaeffer",        era:"Contemporary",  born:1910, died:1995, work:"Musique concrète" },
  { name:"John Cage",               era:"Contemporary",  born:1912, died:1992, work:"4'33\"" },
  { name:"Witold Lutosławski",      era:"Contemporary",  born:1913, died:1994, work:"Symphony No.3" },
  { name:"Iannis Xenakis",          era:"Contemporary",  born:1922, died:2001, work:"Pithoprakta" },
  { name:"György Ligeti",           era:"Contemporary",  born:1923, died:2006, work:"Études" },
  { name:"Luciano Berio",           era:"Contemporary",  born:1925, died:2003, work:"Sinfonia" },
  { name:"Pierre Henry",            era:"Contemporary",  born:1927, died:2017, work:"Variations pour une porte" },
  { name:"Karlheinz Stockhausen",   era:"Contemporary",  born:1928, died:2007, work:"Gruppen" },
  { name:"Toru Takemitsu",          era:"Contemporary",  born:1930, died:1996, work:"November Steps" },
  { name:"Krzysztof Penderecki",    era:"Contemporary",  born:1933, died:2020, work:"Threnody for Hiroshima" },
  { name:"R. Murray Schafer",       era:"Contemporary",  born:1933, died:2021, work:"Apocalypsis" },
  { name:"Peter Maxwell Davies",    era:"Contemporary",  born:1934, died:2016, work:"Eight Songs for a Mad King" },
  { name:"Terry Riley",             era:"Contemporary",  born:1935, died:null,  work:"In C" },
  { name:"Steve Reich",             era:"Contemporary",  born:1936, died:null,  work:"Music for 18 Musicians" },
  { name:"Philip Glass",            era:"Contemporary",  born:1937, died:null,  work:"Einstein on the Beach" },
  { name:"Kaija Saariaho",          era:"Contemporary",  born:1952, died:2023, work:"L'Amour de loin" },
  { name:"Jennifer Higdon",         era:"Contemporary",  born:1962, died:null,  work:"blue cathedral" },
  { name:"Eric Whitacre",           era:"Contemporary",  born:1970, died:null,  work:"Sleep" },
  { name:"Thomas Adès",             era:"Contemporary",  born:1971, died:null,  work:"The Tempest" }
];

// Influence edges for graph (index pairs)
const INFLUENCES = [
  [0,1],[1,2],[2,4],[3,4],[4,5],[5,6],[6,7],[7,8],[8,9],[9,10],[10,13],[11,14],
  [13,14],[14,15],[15,17],[16,18],[17,19],[19,20],[20,21],[21,22],[22,23],[23,25],
  [24,25],[25,26],[26,27],[27,29],[28,29],[29,30],[30,31],[31,32],[32,33],[33,34],
  [34,35],[35,36],[36,37],[37,38],[38,39],[39,40],[40,41],[41,42],[42,43],[43,44],
  [44,45],[45,46],[46,47],[47,48],[25,59],[31,59],[59,60],[60,61],[61,62],[62,63],
  [63,64],[64,65],[65,66],[66,67],[67,68],[68,69],[69,70],[70,71],[71,72],[72,73],
  [73,74],[74,75],[75,76],[76,77],[77,78],[78,79],[79,80],[80,81],[81,82],[82,83],
  [83,84],[84,85],[85,86],[86,87],[87,88],[88,89],[89,90],[90,91],[91,92],[92,93],
  [93,94],[94,95],[95,96],[96,97],[97,98],[98,99],[99,100],[100,101]
];
